/* 添加客户备份表和用户备份表- 2016-01-13 14:02:11 By 陈鹏飞*/
CREATE TABLE `sys_selfcustomerbak` (
  `cus_id` varchar(32) NOT NULL,
  `cus_name` varchar(100) DEFAULT NULL COMMENT '客户名称',
  `cus_cpname` varchar(255) DEFAULT NULL COMMENT '公司英文名',
  `cus_cpename` varchar(255) DEFAULT NULL COMMENT '公司英文名',
  `cus_sex` char(255) DEFAULT NULL COMMENT '客户性别',
  `cus_phone` varchar(255) DEFAULT NULL COMMENT '客户电话',
  `cus_email` varchar(255) DEFAULT NULL COMMENT '邮箱地址',
  `cus_dept` varchar(255) DEFAULT NULL COMMENT '所属部门',
  `cus_pesition` varchar(255) DEFAULT NULL COMMENT '所属职位',
  `cus_desc` varchar(2000) DEFAULT NULL COMMENT '注册原因',
  `creat_time` datetime DEFAULT NULL COMMENT '注册时间',
  `cus_falg` char(1) DEFAULT NULL COMMENT '状态',
  `cus_reason` varchar(2000) DEFAULT NULL COMMENT '审核原因',
  `cus_synopsis` varchar(2000) DEFAULT NULL COMMENT '公司简介',
  `par_user_id` varchar(32) DEFAULT NULL COMMENT '商务人员id',
  `cus_number` varchar(32) DEFAULT NULL COMMENT '客户编号',
  `cus_org` varchar(32) DEFAULT NULL COMMENT '所属客户-客户组织',
  `oper_userid` varchar(32) DEFAULT NULL COMMENT '操作者id',
  `oper_username` varchar(100) DEFAULT NULL COMMENT '操作这名称',
  `user_status` varchar(1) DEFAULT NULL COMMENT '状态',
  `oper_time` datetime DEFAULT NULL COMMENT '操作时间',
  PRIMARY KEY (`cus_id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8;
CREATE TABLE `sys_selfuserbak` (
  `user_id` varchar(32) NOT NULL,
  `user_account` varchar(32) DEFAULT NULL,
  `user_password` varchar(32) DEFAULT NULL,
  `user_person` varchar(100) DEFAULT NULL,
  `user_phone` varchar(32) DEFAULT NULL,
  `user_email` varchar(100) DEFAULT NULL,
  `cus_id` varchar(32) DEFAULT NULL,
  `user_sex` char(1) DEFAULT NULL,
  `last_time` timestamp NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  `role_id` varchar(32) DEFAULT NULL,
  `create_time` timestamp NULL DEFAULT NULL,
  `user_explain` varchar(400) DEFAULT NULL,
  `user_isemailvalid` char(1) DEFAULT NULL,
  `user_isphonevalid` char(1) DEFAULT NULL,
  `is_admin` char(1) DEFAULT '0' COMMENT '是否是超级管理员',
  `salt` varchar(20) DEFAULT NULL,
  `oper_userid` varchar(32) DEFAULT NULL COMMENT '操作者id',
  `oper_username` varchar(100) DEFAULT NULL COMMENT '操作这名称',
  `user_status` varchar(1) DEFAULT NULL COMMENT '状态',
  `oper_time` datetime DEFAULT NULL COMMENT '操作时间',
  PRIMARY KEY (`user_id`),
  KEY `idx_usercusid` (`cus_id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8 ROW_FORMAT=COMPACT;

